### ISSUE TITLE
[Feat]: UPGRADE to App Router

### ISSUE THREAD

**Issue by Jackdrakes** [GalsenDev221/website#101]
### Describe the feature in detail (code, mocks, or screenshots encouraged)

App Router provides more flexibility for nested layouts and data fetching.

### What type of pull request would this be?

Other

**Comment by daoodaba975** [comment]
Hello @Jackdrakes this issue is related to #80 about upgrading Next JS to v14
Can you join this conversation #80 and explain how are you going to approach it before the task is assigned to you.

**Comment by Jackdrakes** [comment]
Sure  @daoodaba975 

Can go through the documentation and upgrading routing to route layout.

Migrating Pages and Hooks .

Must update the Data Fetching methods.
