### ISSUE TITLE
Problem with the website links 

### ISSUE THREAD

**Issue by MedouneSGB** [GalsenDev221/website#49]
Problem switching langages :
Fr <--> En
We have to do the action 2 times to refresh the page.

![image](https://github.com/GalsenDev221/website/assets/40875400/52081eff-77f9-4efa-a215-22d7668536ab)

**Comment by NDOY3M4N** [comment]
Hi @MedouneSGB. I tested on my end and apparently it's all the links on the navbar. I don't know if it's related to `Link`.

**Comment by MedouneSGB** [comment]
Hello @NDOY3M4N, 
Oh you're right, it looks more global.

**Comment by daoodaba975** [comment]
I hadn't noticed that, we'll have to inspect all of this to find the problem.

**Comment by cirejr** [comment]
Salam y'all 
I am a newcomer and would like to contribute
