### ISSUE TITLE
The buttons are too wide

### ISSUE THREAD

**Issue by NDOY3M4N** [GalsenDev221/website#79]
![image](https://github.com/GalsenDev221/website/assets/46305144/a3e3b738-b7ad-47ed-9ea2-13b600ca908c)

We could reduce the padding.

**Comment by hakimLyon** [comment]
https://github.com/GalsenDev221/website/assets/64654633/9c1650b5-1e69-4ac2-84c5-bee0e7a1fd88

C'est peut-être la responsivité qu'on devrait vérifier ? Je ne sais pas quelle est la taille de l'écran de ton screenshot, il faut l'ajuster en fonction de cela je crois !

**Comment by hakimLyon** [comment]
> Enregistrement.de.l.ecran.2023-11-27.a.01.43.58.mov 
> It might be the responsiveness that we should check? I don't know what the screen size of your screenshot is, and we need to adjust it accordingly!

I see, it's the English version that is lacking.

**Comment by hakimLyon** [comment]
I have a suggestion, we can just shorten the title to 'View pictures.'
<img width="1370" alt="Capture d’écran 2023-11-27 à 01 57 06" src="https://github.com/GalsenDev221/website/assets/64654633/c00dfd09-238a-4884-ad7c-03b0410cbbef">

**Comment by hakimLyon** [comment]
https://github.com/GalsenDev221/website/assets/64654633/f44ed2fd-42c0-4b18-ada6-54fb1557de56

**Comment by NDOY3M4N** [comment]
Yup this nicely fixes the problem
