### ISSUE TITLE
Hero image too small

### ISSUE THREAD

**Issue by NDOY3M4N** [GalsenDev221/website#81]
![image](https://github.com/GalsenDev221/website/assets/46305144/c70593ab-d3da-4069-b18f-4910263256a0)

On some devices the hero image is too small somehow. I tested it on Firefox

**Comment by modouaicha023** [comment]
Hi there! I'd like to take a shot at fixing this. Once I have a clearer understanding, I'll propose a solution and submit a pull request.

**Comment by daoodaba975** [comment]
Nice @modouaicha023 you're welcome !
@NDOY3M4N can you add more explanation on this issue.

**Comment by modouaicha023** [comment]
@daoodaba975 You can reproduce the bug in Firefox by zooming in from 110%. I maybe have a solution, i'm gonna try fixing it

**Comment by NDOY3M4N** [comment]
Yup, just tested it on the Brave browser too and it's the same issue. I think this is related to the `flex` style defined in the hero container. If you would like, we can assign you this issue @modouaicha023

**Comment by modouaicha023** [comment]
@NDOY3M4N Thanks for that information. I'll take a closer look at the flex style. You can assign me to this issue.
