### ISSUE TITLE
[Bug]: the `Space_Grotesk` font-family is not used in the navbar

### ISSUE THREAD

**Issue by NDOY3M4N** [GalsenDev221/website#82]
### Current Behavior

The navbar just uses the default font provided by the browser.

### Expected Behavior

I think we should use the `Space Grotesk` font in the navbar too since it's used everywhere else on the website

### What browsers are you seeing the problem on?

Firefox, Chrome, Safari, Microsoft Edge

**Comment by daoodaba975** [comment]
Same for the Footer also @NDOY3M4N 
The issue is general; I tested it on Chrome, Edge, and Safari.
